/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecordCategory = IDL.Variant({
  'arac' : IDL.Null,
  'esya' : IDL.Null,
  'insan' : IDL.Null,
  'hayvan' : IDL.Null,
});
export const AracKaydi = IDL.Record({
  'marka' : IDL.Text,
  'model' : IDL.Text,
  'contactInfo' : IDL.Text,
  'renk' : IDL.Text,
  'contactPerson' : IDL.Text,
  'plaka' : IDL.Text,
});
export const EsyaKaydi = IDL.Record({
  'marka' : IDL.Text,
  'contactInfo' : IDL.Text,
  'esyaAdi' : IDL.Text,
  'contactPerson' : IDL.Text,
  'seriNo' : IDL.Text,
  'aciklama' : IDL.Text,
});
export const InsanKaydi = IDL.Record({
  'yas' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'contactPerson' : IDL.Text,
  'iliski' : IDL.Text,
  'aciklama' : IDL.Text,
  'adSoyad' : IDL.Text,
});
export const HayvanKaydi = IDL.Record({
  'ad' : IDL.Text,
  'tur' : IDL.Text,
  'contactInfo' : IDL.Text,
  'notlar' : IDL.Text,
  'renk' : IDL.Text,
  'contactPerson' : IDL.Text,
});
export const RecordData = IDL.Variant({
  'arac' : AracKaydi,
  'esya' : EsyaKaydi,
  'insan' : InsanKaydi,
  'hayvan' : HayvanKaydi,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userCode' : IDL.Text,
  'username' : IDL.Text,
});
export const QREncodedData = IDL.Record({
  'contactInfo' : IDL.Text,
  'displayText' : IDL.Text,
  'contactPerson' : IDL.Text,
  'uniqueCode' : IDL.Text,
});
export const Time = IDL.Int;
export const UserRecord = IDL.Record({
  'userCode' : IDL.Text,
  'username' : IDL.Text,
  'qrEncodedData' : QREncodedData,
  'creationTimestamp' : Time,
  'recordData' : RecordData,
  'uniqueCode' : IDL.Text,
  'category' : RecordCategory,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNewRecord' : IDL.Func(
      [IDL.Text, RecordCategory, RecordData, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewUserCode' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], []),
  'generateShareableLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getAllRecordsForUser' : IDL.Func([IDL.Text], [IDL.Vec(UserRecord)], []),
  'getAllUserCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfileByUserCode' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], []),
  'getRecordByShareableLink' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserRecord)],
      ['query'],
    ),
  'getRecordByUniqueCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecordCategory = IDL.Variant({
    'arac' : IDL.Null,
    'esya' : IDL.Null,
    'insan' : IDL.Null,
    'hayvan' : IDL.Null,
  });
  const AracKaydi = IDL.Record({
    'marka' : IDL.Text,
    'model' : IDL.Text,
    'contactInfo' : IDL.Text,
    'renk' : IDL.Text,
    'contactPerson' : IDL.Text,
    'plaka' : IDL.Text,
  });
  const EsyaKaydi = IDL.Record({
    'marka' : IDL.Text,
    'contactInfo' : IDL.Text,
    'esyaAdi' : IDL.Text,
    'contactPerson' : IDL.Text,
    'seriNo' : IDL.Text,
    'aciklama' : IDL.Text,
  });
  const InsanKaydi = IDL.Record({
    'yas' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'contactPerson' : IDL.Text,
    'iliski' : IDL.Text,
    'aciklama' : IDL.Text,
    'adSoyad' : IDL.Text,
  });
  const HayvanKaydi = IDL.Record({
    'ad' : IDL.Text,
    'tur' : IDL.Text,
    'contactInfo' : IDL.Text,
    'notlar' : IDL.Text,
    'renk' : IDL.Text,
    'contactPerson' : IDL.Text,
  });
  const RecordData = IDL.Variant({
    'arac' : AracKaydi,
    'esya' : EsyaKaydi,
    'insan' : InsanKaydi,
    'hayvan' : HayvanKaydi,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userCode' : IDL.Text,
    'username' : IDL.Text,
  });
  const QREncodedData = IDL.Record({
    'contactInfo' : IDL.Text,
    'displayText' : IDL.Text,
    'contactPerson' : IDL.Text,
    'uniqueCode' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserRecord = IDL.Record({
    'userCode' : IDL.Text,
    'username' : IDL.Text,
    'qrEncodedData' : QREncodedData,
    'creationTimestamp' : Time,
    'recordData' : RecordData,
    'uniqueCode' : IDL.Text,
    'category' : RecordCategory,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNewRecord' : IDL.Func(
        [IDL.Text, RecordCategory, RecordData, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewUserCode' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], []),
    'generateShareableLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getAllRecordsForUser' : IDL.Func([IDL.Text], [IDL.Vec(UserRecord)], []),
    'getAllUserCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfileByUserCode' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], []),
    'getRecordByShareableLink' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserRecord)],
        ['query'],
      ),
    'getRecordByUniqueCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };