/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AracKaydi {
  'marka' : string,
  'model' : string,
  'contactInfo' : string,
  'renk' : string,
  'contactPerson' : string,
  'plaka' : string,
}
export interface EsyaKaydi {
  'marka' : string,
  'contactInfo' : string,
  'esyaAdi' : string,
  'contactPerson' : string,
  'seriNo' : string,
  'aciklama' : string,
}
export interface HayvanKaydi {
  'ad' : string,
  'tur' : string,
  'contactInfo' : string,
  'notlar' : string,
  'renk' : string,
  'contactPerson' : string,
}
export interface InsanKaydi {
  'yas' : bigint,
  'contactInfo' : string,
  'contactPerson' : string,
  'iliski' : string,
  'aciklama' : string,
  'adSoyad' : string,
}
export interface QREncodedData {
  'contactInfo' : string,
  'displayText' : string,
  'contactPerson' : string,
  'uniqueCode' : string,
}
export type RecordCategory = { 'arac' : null } |
  { 'esya' : null } |
  { 'insan' : null } |
  { 'hayvan' : null };
export type RecordData = { 'arac' : AracKaydi } |
  { 'esya' : EsyaKaydi } |
  { 'insan' : InsanKaydi } |
  { 'hayvan' : HayvanKaydi };
export type Time = bigint;
export interface UserProfile { 'userCode' : string, 'username' : string }
export interface UserRecord {
  'userCode' : string,
  'username' : string,
  'qrEncodedData' : QREncodedData,
  'creationTimestamp' : Time,
  'recordData' : RecordData,
  'uniqueCode' : string,
  'viewCount' : bigint,
  'category' : RecordCategory,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNewRecord' : ActorMethod<
    [string, RecordCategory, RecordData, string, string],
    [] | [string]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNewUserCode' : ActorMethod<[string], [] | [UserProfile]>,
  'deleteRecord' : ActorMethod<[string, string], boolean>,
  'generateShareableLink' : ActorMethod<[string], [] | [string]>,
  'getAllRecordsForUser' : ActorMethod<[string], Array<UserRecord>>,
  'getAllUserCodes' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfileByUserCode' : ActorMethod<[string], [] | [UserProfile]>,
  'getRecordByShareableLink' : ActorMethod<[string], [] | [UserRecord]>,
  'getRecordByUniqueCode' : ActorMethod<[string], [] | [UserRecord]>,
  'getRecordViewCount' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementViewCount' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRecordData' : ActorMethod<[string, RecordData], boolean>,
  'updateRecordLocation' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];