/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EsyaKaydi {
    marka: string;
    contactInfo: string;
    esyaAdi: string;
    contactPerson: string;
    seriNo: string;
    aciklama: string;
}
export interface AracKaydi {
    marka: string;
    model: string;
    contactInfo: string;
    renk: string;
    contactPerson: string;
    plaka: string;
}
export type Time = bigint;
export interface HayvanKaydi {
    ad: string;
    tur: string;
    contactInfo: string;
    notlar: string;
    renk: string;
    contactPerson: string;
}
export type RecordData = {
    __kind__: "arac";
    arac: AracKaydi;
} | {
    __kind__: "esya";
    esya: EsyaKaydi;
} | {
    __kind__: "insan";
    insan: InsanKaydi;
} | {
    __kind__: "hayvan";
    hayvan: HayvanKaydi;
};
export interface QREncodedData {
    contactInfo: string;
    displayText: string;
    contactPerson: string;
    uniqueCode: string;
}
export interface InsanKaydi {
    yas: bigint;
    contactInfo: string;
    contactPerson: string;
    iliski: string;
    aciklama: string;
    adSoyad: string;
}
export interface UserRecord {
    userCode: string;
    username: string;
    qrEncodedData: QREncodedData;
    creationTimestamp: Time;
    recordData: RecordData;
    uniqueCode: string;
    category: RecordCategory;
}
export interface UserProfile {
    userCode: string;
    username: string;
}
export enum RecordCategory {
    arac = "arac",
    esya = "esya",
    insan = "insan",
    hayvan = "hayvan"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNewRecord(userCode: string, category: RecordCategory, recordData: RecordData, contactPerson: string, contactInfo: string): Promise<string | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createNewUserCode(username: string): Promise<UserProfile | null>;
    generateShareableLink(recordId: string): Promise<string | null>;
    getAllRecordsForUser(userCode: string): Promise<Array<UserRecord>>;
    getAllUserCodes(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProfileByUserCode(userCode: string): Promise<UserProfile | null>;
    getRecordByShareableLink(linkId: string): Promise<UserRecord | null>;
    getRecordByUniqueCode(code: string): Promise<UserRecord | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AracKaydi as _AracKaydi, EsyaKaydi as _EsyaKaydi, HayvanKaydi as _HayvanKaydi, InsanKaydi as _InsanKaydi, QREncodedData as _QREncodedData, RecordCategory as _RecordCategory, RecordData as _RecordData, Time as _Time, UserProfile as _UserProfile, UserRecord as _UserRecord, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNewRecord(arg0: string, arg1: RecordCategory, arg2: RecordData, arg3: string, arg4: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewRecord(arg0, to_candid_RecordCategory_n1(this._uploadFile, this._downloadFile, arg1), to_candid_RecordData_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewRecord(arg0, to_candid_RecordCategory_n1(this._uploadFile, this._downloadFile, arg1), to_candid_RecordData_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNewUserCode(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewUserCode(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewUserCode(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateShareableLink(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateShareableLink(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateShareableLink(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecordsForUser(arg0: string): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecordsForUser(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecordsForUser(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserCodes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserCodes();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByUserCode(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByUserCode(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByUserCode(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecordByShareableLink(arg0: string): Promise<UserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordByShareableLink(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordByShareableLink(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecordByUniqueCode(arg0: string): Promise<UserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordByUniqueCode(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordByUniqueCode(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_RecordCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordCategory): RecordCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RecordData_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordData): RecordData {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRecord): UserRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRecord]): UserRecord | null {
    return value.length === 0 ? null : from_candid_UserRecord_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userCode: string;
    username: string;
    qrEncodedData: _QREncodedData;
    creationTimestamp: _Time;
    recordData: _RecordData;
    uniqueCode: string;
    category: _RecordCategory;
}): {
    userCode: string;
    username: string;
    qrEncodedData: QREncodedData;
    creationTimestamp: Time;
    recordData: RecordData;
    uniqueCode: string;
    category: RecordCategory;
} {
    return {
        userCode: value.userCode,
        username: value.username,
        qrEncodedData: value.qrEncodedData,
        creationTimestamp: value.creationTimestamp,
        recordData: from_candid_RecordData_n12(_uploadFile, _downloadFile, value.recordData),
        uniqueCode: value.uniqueCode,
        category: from_candid_RecordCategory_n14(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arac: _AracKaydi;
} | {
    esya: _EsyaKaydi;
} | {
    insan: _InsanKaydi;
} | {
    hayvan: _HayvanKaydi;
}): {
    __kind__: "arac";
    arac: AracKaydi;
} | {
    __kind__: "esya";
    esya: EsyaKaydi;
} | {
    __kind__: "insan";
    insan: InsanKaydi;
} | {
    __kind__: "hayvan";
    hayvan: HayvanKaydi;
} {
    return "arac" in value ? {
        __kind__: "arac",
        arac: value.arac
    } : "esya" in value ? {
        __kind__: "esya",
        esya: value.esya
    } : "insan" in value ? {
        __kind__: "insan",
        insan: value.insan
    } : "hayvan" in value ? {
        __kind__: "hayvan",
        hayvan: value.hayvan
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arac: null;
} | {
    esya: null;
} | {
    insan: null;
} | {
    hayvan: null;
}): RecordCategory {
    return "arac" in value ? RecordCategory.arac : "esya" in value ? RecordCategory.esya : "insan" in value ? RecordCategory.insan : "hayvan" in value ? RecordCategory.hayvan : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserRecord>): Array<UserRecord> {
    return value.map((x)=>from_candid_UserRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_RecordCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordCategory): _RecordCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RecordData_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordData): _RecordData {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordCategory): {
    arac: null;
} | {
    esya: null;
} | {
    insan: null;
} | {
    hayvan: null;
} {
    return value == RecordCategory.arac ? {
        arac: null
    } : value == RecordCategory.esya ? {
        esya: null
    } : value == RecordCategory.insan ? {
        insan: null
    } : value == RecordCategory.hayvan ? {
        hayvan: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "arac";
    arac: AracKaydi;
} | {
    __kind__: "esya";
    esya: EsyaKaydi;
} | {
    __kind__: "insan";
    insan: InsanKaydi;
} | {
    __kind__: "hayvan";
    hayvan: HayvanKaydi;
}): {
    arac: _AracKaydi;
} | {
    esya: _EsyaKaydi;
} | {
    insan: _InsanKaydi;
} | {
    hayvan: _HayvanKaydi;
} {
    return value.__kind__ === "arac" ? {
        arac: value.arac
    } : value.__kind__ === "esya" ? {
        esya: value.esya
    } : value.__kind__ === "insan" ? {
        insan: value.insan
    } : value.__kind__ === "hayvan" ? {
        hayvan: value.hayvan
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
